name: Test workflow for Python template
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Create virtual env
      run: |
        make env
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Format code
      run: |
        make format
    - name: Test with unittest
      run: |
        make test
  

    
    

    
    
